#!/bin/bash

{% if firstrun==True %}
mkdir -p {{ DIR }}
mkdir {{ PFADRES }}
mkdir {{ MYWRKHOME }}/log
mkdir {{ MYWRKSHR }}/hclake
    {% for xfolder in xfolders %}
mkdir {{ DIR }}/{{ xfolder }}
    {% endfor %}
{% endif %}

rm {{ DIR }}/xe/e{{ USER }}{{ EXP }}e_c???_{{ year }}{{ mon }}

cd {{ PFADFRC }}
echo unpacking a{{ BUSER }}{{ BEXP }}a{{ year }}{{ mon }}.tar
tar -xf a{{ BUSER }}{{ BEXP }}a{{ year }}{{ mon }}.tar -C {{ DIR }}/xa/
echo unpacking a{{ BUSER }}{{ BEXP }}a{{ nyear }}{{ nmon }}.tar
tar -xf a{{ BUSER }}{{ BEXP }}a{{ nyear }}{{ nmon }}.tar -C {{ DIR }}/xa/
echo done




